### ISSUE TITLE
Mesh Visualization Issue with Fluent Case file

### ISSUE THREAD

**Issue by abhishekchitwar** [pyansys/pyfluent-visualization#228]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

ran the following code snippet for Mesh Visualization, However got stuck with following issue while defining mesh object
 
Failed to run with following version;
ansys-fluent-core                     0.13.dev2
ansys-fluent-visualization            0.6.0  

```python

import ansys.fluent.core as pyfluent
from ansys.fluent.visualization.pyvista import Graphics

session = pyfluent.launch_fluent(show_gui=True)
session.file.read_case(file_name='elbow1.cas.h5')

graphics = Graphics(session=session)    
mesh1 = graphics.Meshes['mesh-1']

```
Traceback

```error
>>> mesh1 = graphics.Meshes["mesh-1"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\pythonProject\Viewer_Test\.venv\lib\site-packages\ansys\fluent\core\meta.py", line 413, in __getitem__
    o = self.__collection[name] = self.__object_class(
  File "d:\pythonProject\Viewer_Test\.venv\lib\site-packages\ansys\fluent\core\meta.py", line 351, in wrapper
    self._api_helper = api_helper(self)
TypeError: 'NoneType' object is not callable

```

Kindly note that, Same code snippet is working fine with following version;
ansys-fluent-core                     0.12.3
ansys-fluent-visualization            0.6.0

### 📝 Steps to reproduce

Please run the above mentioned code snippet with any Fluent case file

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

ANSYS Fluent 2023 R2

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
Package                               Version
------------------------------------- ---------
ansys-api-fluent                      0.3.7    
ansys-api-platform-instancemanagement 1.0.0b3  
ansys-fluent-core                     0.13.dev2
ansys-fluent-visualization            0.6.0    
ansys-platform-instancemanagement     1.0.3    
appdirs                               1.4.4    
asttokens                             2.2.1    
backcall                              0.2.0    
certifi                               2022.12.7
charset-normalizer                    3.0.1    
click                                 8.1.3    
colorama                              0.4.6    
comm                                  0.1.2    
contourpy                             1.0.7    
cycler                                0.11.0   
dash                                  2.8.1    
dash-bootstrap-components             1.3.1    
dash-core-components                  2.0.0    
dash-html-components                  2.0.0    
dash-table                            5.0.0    
dash-vtk                              0.0.9    
debugpy                               1.6.6    
decorator                             5.1.1    
executing                             1.2.0    
Flask                                 2.2.3    
fonttools                             4.38.0   
googleapis-common-protos              1.58.0   
grpcio                                1.51.3   
h5py                                  3.8.0    
idna                                  3.4      
imageio                               2.26.0   
importlib-metadata                    6.0.0    
importlib-resources                   5.12.0   
ipydatawidgets                        4.3.3    
ipykernel                             6.21.2   
ipython                               8.10.0   
ipywidgets                            8.0.4    
itsdangerous                          2.1.2    
jedi                                  0.18.2   
Jinja2                                3.1.2    
jupyter_client                        8.0.3    
jupyter_core                          5.2.0    
jupyterlab-widgets                    3.0.5    
kiwisolver                            1.4.4    
MarkupSafe                            2.1.2    
matplotlib                            3.7.0
matplotlib-inline                     0.1.6
nest-asyncio                          1.5.6
numpy                                 1.24.2
packaging                             23.0
pandas                                1.5.3
parso                                 0.8.3
pickleshare                           0.7.5
Pillow                                9.4.0
pip                                   22.2.2
platformdirs                          3.0.0
plotly                                5.13.1
pooch                                 1.6.0
prompt-toolkit                        3.0.37
protobuf                              3.20.3
protoc-gen-swagger                    0.1.0
psutil                                5.9.4
pure-eval                             0.2.2
Pygments                              2.14.0
pyparsing                             3.0.9
PySide6                               6.4.2
PySide6-Addons                        6.4.2
PySide6-Essentials                    6.4.2
python-dateutil                       2.8.2
pythreejs                             2.4.2
pytz                                  2022.7.1        
pyvista                               0.38.3
pyvistaqt                             0.9.1
pywin32                               305
pyzmq                                 25.0.0
QtPy                                  2.3.0
requests                              2.28.2
scooby                                0.7.1
setuptools                            65.4.1
shiboken6                             6.4.2
six                                   1.16.0
stack-data                            0.6.2
tenacity                              8.2.1
tornado                               6.2
traitlets                             5.9.0
traittypes                            0.2.1
urllib3                               1.26.14
vtk                                   9.2.6
wcwidth                               0.2.6
Werkzeug                              2.2.3
wheel                                 0.37.1
widgetsnbextension                    4.0.5
zipp                                  3.15.0

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
```

**Comment by prmukherj** [comment]
This issue is fixed after the 0.13.dev3 release of the core repo.
Thank you
cc. @ajain-work
